# Generated by Django 5.0.6 on 2024-07-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='billing_city',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_house',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_street',
        ),
    ]
