# Generated by Django 5.0.6 on 2024-07-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_stripe_card_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_card_token',
        ),
    ]
