# Generated by Django 5.0.6 on 2024-08-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='shipping_first_name',
            new_name='full_name',
        ),
    ]
