# Generated by Django 5.0.6 on 2024-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
