# Generated by Django 5.0.6 on 2024-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_description_en_product_description_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_it',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
