# Generated by Django 5.0.6 on 2024-07-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_tag_name_en_tag_name_it_tag_name_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_tr',
        ),
    ]
