# Generated by Django 5.0.6 on 2024-08-01 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_tag_name_en_remove_tag_name_it_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 1, 9, 38, 54, 446841, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
