# Generated by Django 5.0.6 on 2024-08-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_favorite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/noimage_detail.png', upload_to='products/'),
        ),
    ]
